services:
  db:
    image: postgres
    container_name: db-4
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - myappdb_volume:/var/lib/postgresql/data
    networks:
      - myappdb_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
       .
    image: umamaheswarigude11/backend:v4
    container_name: backend-4
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    networks:
      - myappdb_network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5050/health-check"]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
        db:
          condition: service_healthy
volumes:
  myappdb_volume:
networks:
  myappdb_network:






