name: fullstack-application

on:
  push:
    branches: [ "main", "feature/docker-setup" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend 

      - name: Build project for backend
        run: npm run build
        working-directory: ./backend


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
            cat <<EOF > .env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT= 5432
            DB_NAME= myappdb
            DB_HOST= db
            EOF
          
      - name: Docker compose
        run: docker compose up --build


