name: fullstack-application

on:
  push:
    branches: [ "main", "feature/docker-setup" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend 

      - name: Build project for backend
        run: npm run build
        working-directory: ./backend


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env
          echo DB_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_PORT=${{ secrets.POSTGRES_KEY }} >> .env
          echo DB_NAME=${{ secrets.POSTGRES_KEY }} >> .env
          echo DB_HOST=${{ secrets.POSTGRES_KEY }} >> .env
          cat .env
          
      - name: Docker compose
        run: docker compose up --build


